### ISSUE TITLE
CICD for LaTeX thesis

### ISSUE THREAD

**Issue by ElectroluxV2** [EngineerDiplomaTeam/city-map-planner#17]
We want to add compile check for PRs that modify aything from /Documentation (Rename from /Documentary)
so nobody will break compilation of latex.

On main branch, CICD should publish output PDF as static assets avaliable at:
https://city-planner.budziszm.pl/thesis (serve only latest version)

**Comment by damiankreft** [comment]
We'll also need .gitignore entries to prevent us from adding LaTeX compilation artifacts to the repo

**Comment by ElectroluxV2** [comment]
For me these are:

thesis.aux
thesis.log
thesis.out
thesis.pdf
thesis.synctex.gz
thesis.toc

**Comment by ElectroluxV2** [comment]
I guess we can exclude thesis* except thesis.tex.
