### ISSUE TITLE
Technology choices chapter

### ISSUE THREAD

**Issue by ElectroluxV2** [EngineerDiplomaTeam/city-map-planner#31]
Write chapter about technology choices

**Comment by WertiPL** [comment]
Edited to required form

**Comment by ElectroluxV2** [comment]
przypisujesz sobie za to 10 godzin? pls zrób osobny task, ja jak ci coś poprawiałem to wpisywałem to osobno

**Comment by WertiPL** [comment]
> przypisujesz sobie za to 10 godzin? pls zrób osobny task, ja jak ci coś poprawiałem to wpisywałem to osobno

żeby przypisać sobie bym musiał być w assign a tylko dodałem komentarz
;d
