### ISSUE TITLE
Store project documentation inside repository

### ISSUE THREAD

**Issue by ElectroluxV2** [EngineerDiplomaTeam/city-map-planner#5]
Upload copy of each project related document to the <repo root>/documentation directory.

**Comment by WertiPL** [comment]
Every File is shared for everyone under this link https://pejot-my.sharepoint.com/:f:/g/personal/s23141_pjwstk_edu_pl/Evv7oka36I9OpkpZWIumbMsBRDOLirWg9zAQdSVw1XpPPQ?e=tN6zYN

I think that we should finished it online and after it send to repo

**Comment by ElectroluxV2** [comment]
Dont agree, separate this to another card.
