### ISSUE TITLE
List of attractions in Gdańsk

### ISSUE THREAD

**Issue by ElectroluxV2** [EngineerDiplomaTeam/city-map-planner#62]
Prepare a list of tourist attractions in Gdansk, each attraction should consist of:
- name 
- link to the website with opening hours 
- a link to a page with a description
- geographical coordinates of the beginning
- geographical coordinates of the end
Coordinates should be from https://www.openstreetmap.org (right click, show address)
Insert list as attachment

**Comment by damiankreft** [comment]
Powiązane z #66

**Comment by WertiPL** [comment]
@ElectroluxV2 [LINK do Excel z danymi]( https://pejot-my.sharepoint.com/:x:/g/personal/s23141_pjwstk_edu_pl/EZ6_gok5GANNtcvMdK0M-koBCGl1gZ_13GKxHmfPTzgbiw?e=qU5tG1)

Potrzebuje pomocy z decyzją schematu dotyczącą godzin gdyż jest wiele wyjątkow jak do tego podchodzimy żeby  było optymalnie w tym momencie propozycja widoczna pod linkiem, dokładniejsze pytanie w komentarzu

**Comment by ElectroluxV2** [comment]
Po co Ci to teraz wiedzieć? Tu trzeba tylko dać link do strony z godzinami otwarcia, nic więcej.
@damiankreft napisał, że #66 jest powiązane, tu: https://github.com/EngineerDiplomaTeam/city-map-planner/issues/66#issuecomment-1970104730, napisałem jak widzę trzymanie godzin otwarcia.

**Comment by WertiPL** [comment]
@ElectroluxV2 Wszystko co chciałeś jest w pliku do twojego założenia, też  spełniłem przy okazji dane dla @damiankreft i te, którę może się przydadzą [LINK do POI](https://pejot-my.sharepoint.com/:x:/g/personal/s23141_pjwstk_edu_pl/EZ6_gok5GANNtcvMdK0M-koBCGl1gZ_13GKxHmfPTzgbiw?e=YbkYM1)

**Comment by WertiPL** [comment]
@ElectroluxV2 node added
