### ISSUE TITLE
Przygotowanie struktury tabel dot. POI

### ISSUE THREAD

**Issue by damiankreft** [EngineerDiplomaTeam/city-map-planner#66]
Oczekiwane produkty: SQL do utworzenia bazy, schematy/diagramy do książki

Należy przygotować strukturę bazy danych do przechowywania danych (atrakcji i pokrywnych)

- nazwa
- opis
- zdjecie / header
- koordynaty
- Zalecana długość zwiedzania - uwzględniania przez algorytm planowania wycieczki
- godzina otwarcia
- godzina zamknięcia
- preferowana pogoda
- ocena
- opinie użytkowników
- ??? plany zwiedzania użytkowników

**Comment by ElectroluxV2** [comment]
Ja pogodę widzę tak: require i include, obydwa pola opcjonalne i mogą zawierać n tagów opisanych w #75

**Comment by ElectroluxV2** [comment]
Myślę, że godziny otwarcia / zamknięcia muszą być osobną tabelą: idAtrakcji, timestamp from, timestamp to, status

**Comment by ElectroluxV2** [comment]
koordynaty - to IMHO też musi być osobna tabela: idAtrakcji, nodeId z bazy z grafem połączeń (czyli defacto współrzędne geograficzne, ale wpięte w graf), description, default.

Gdzie opis pokażemy userowi jako opcja do wyboru
A pole default będzie ustawione przez nas, każda atrakcja musi mieć przynajmniej 1 rekord z default = begin i 1 rekord z default = end.

To pozwoli na to co dziekan mówił: Co jeśli atrakcja ma kilka wejść albo wyjście jest w innym miejscu niż wejście.

**Comment by ElectroluxV2** [comment]
ocena
opinie użytkowników
??? plany zwiedzania użytkowników
Możemy napisać w książce o tym, ale ja będę się upierał, żeby zrobić to jako ostatni feature ever, bo to bardzo mało istotne.

**Comment by WertiPL** [comment]
> Myślę, że godziny otwarcia / zamknięcia muszą być osobną tabelą: idAtrakcji, timestamp from, timestamp to, status

Jak najbardziej trzeba iść w tą strone gdyż musimy brać pod uwagę
różne godziny w różnych miesiącach ( inne godzinny otwarcia są od kwietnia do czerwca inne od lipca do sierpnia itd)
inne godziny są dla każdego dnia w tygodniu np. wtorek i poniedziałek 

Niektóre dni są zamkniete przez święta lub z góry wyznaczone dni konserwacyjne
Moja propozycja jest jak niżej
ID | Date_From | Date_To | Day_Of_Week | Hour_Start | Hour_Close | Ticket-Close | Ticket-Open | Close_day | POI_id

0 | 1-Sep | 6/30/2024 | 0 | 10:00 | 18:00 | 17:00 | 9:30 | 0 | 0

**Comment by ElectroluxV2** [comment]
Zaproponuj jakbys widział rekord w bazie atrakcji która ma zawsze otwarte kasy biletowe (sprzedaż tylko online) ale jest zamknięta w poniedziałki

**Comment by WertiPL** [comment]
Przewidziałem w strukturze jest link do sklepu online w tabeli atrakcji


Jak niżej każdy dzień jest indywidualny
Zakres od miesiąca do miesiąca, dzień od 0-6 , Close_day dla przyszpieszenia algorytymu
ID | Date_From | Date_To | Day_Of_Week | Hour_Start | Hour_Close | Ticket-Close | Ticket-Open | Close_day | POI_id
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | 1-Sep | 6/30/2024 | 0 | 10:00 | 18:00 | 0 | 0 | 0 | 0
0 | 2-Sep | 6/30/2024 | 1 | 10:00 | 16:00 | 15:00 | 9:30 | 0 | 0

**Comment by WertiPL** [comment]
Jednej rzeczy jakiej nie przewidziałem, a powinno być dodany kolejny rekord dla dni otwarty "Wstęp darmowy"

**Comment by damiankreft** [comment]
IMO za dużo primitive type'ów i przy pierwszej lepszej zmianie wymagań narzuconej przez dziekana mogłoby się to skończyć przerabianiem w wielu miejscach. 

Nie ma co kombinować z dziwnymi wartościami typu 9999 dla wstępu darmowego tylko trzeba to sensownie zaprojektować, żebyśmy takie dane mogli normalnie wyciągać. Podejrzewam, że dziekan od razu by pytał o co chodzi z 9999 i dlaczego nie jest inaczej.

Zgrubny zarys samego PointOfInterest wyglądałby mniej więcej tak jak na załączonym obrazku. Rzeczy pokroju przedziałów czasowych wolałbym przechowywać w formie kolekcji pojedynczych obiektów przechowujących zestawy wartości opisujące konkretne zjawiska. To powinno pozwolić na sensowną utrzymywalność na wypadek zmian w koncepcji pracy inżynierskiej
![image](https://github.com/EngineerDiplomaTeam/city-map-planner/assets/25139693/d30dd566-6a45-4d66-ba5a-6ecee429437d)

**Comment by WertiPL** [comment]
Moja propozycja dotyczy tylko godzin gdyż jest zbyt duży rozstrzał dla jednej atrakcji jest dochodzi do przynajmniej 10 różnych wariantów godzin otwarcia zależnych od miesiąca, dnia tygodnia, święta etc

**Comment by damiankreft** [comment]
Zalozylem, że problem godzin otwarcia to jeden z najpopularniejszych problemów domenowych, i jak widzę, nie myliłem się. Tutaj jest rozwiązanie problemu:

https://stackoverflow.com/questions/24294524/how-to-model-the-opening-times-of-shops-in-an-object-oriented-way

**Comment by damiankreft** [comment]
Poza tym proponuję zaskoczyć Dziekana i jeszcze dodać informację o strefie czasowej przy godzinach otwarcia atrakcji.

Przy założeniu, że mówiliśmy o możliwości i8n aplikacji, może się przyczepić o to, że nie ma informacji o strefie czasowej, a od strony kodu nie powinno to być skomplikowane. C# posiada możliwości konwersji pomiedzy strefami czasowymi:

https://learn.microsoft.com/en-us/dotnet/standard/datetime/converting-between-time-zones#converting-utc-to-a-designated-time-zone

**Comment by WertiPL** [comment]
> Poza tym proponuję zaskoczyć Dziekana i jeszcze dodać informację o strefie czasowej przy godzinach otwarcia atrakcji.
> 
> Przy założeniu, że mówiliśmy o możliwości i8n aplikacji, może się przyczepić o to, że nie ma informacji o strefie czasowej, a od strony kodu nie powinno to być skomplikowane. C# posiada możliwości konwersji pomiedzy strefami czasowymi:
> 
> https://learn.microsoft.com/en-us/dotnet/standard/datetime/converting-between-time-zones#converting-utc-to-a-designated-time-zone

Bardzo podoba mi się pomysł

**Comment by WertiPL** [comment]
> Zalozylem, że problem godzin otwarcia to jeden z najpopularniejszych problemów domenowych, i jak widzę, nie myliłem się. Tutaj jest rozwiązanie problemu:
> 
> https://stackoverflow.com/questions/24294524/how-to-model-the-opening-times-of-shops-in-an-object-oriented-way
> 
> 
> Przykład:
> ![20240309_093958](https://github.com/EngineerDiplomaTeam/city-map-planner/assets/25139693/8b1545d6-a062-4fb4-91fb-04b74dcdb62b)
> 

powiesz mi w przerwie jak to technicznie się różni w implementacji względem mojej propozycji?

rozumiem to jako przykład bo nie obejmuje wszystkich parametrów które potrzebujemy jak przypuszczam
