### ISSUE TITLE
Integracja z API pogodowym - rozbicie bogatej informacji pogodowej na kilka kategorii pogodowych

### ISSUE THREAD

**Issue by damiankreft** [EngineerDiplomaTeam/city-map-planner#75]
Integracja z API pogodowym - rozbicie bogatej informacji pogodowej na kilka kategorii pogodowych, którymi będziemy operować w aplikacji, typu: deszcz, bezchmurnie, wietrznie? itd

Kiedy zaciągniemy dane z API to będą bardzo bogate w informacje - będziemy potrzebowali trochę "spłaszczyć" te dane i podzielić na kategorie pogodowe. Innymi słowy dokonać klasyfikacji - podzielić na klasy :)

**Comment by ElectroluxV2** [comment]
Znalazłem ciekawe API: https://open-meteo.com/en/docs
To pozwoliło by nam zawęzić klasyfikację, proponuje takie tagi pogodowe jak podają w description:
![image](https://github.com/EngineerDiplomaTeam/city-map-planner/assets/29741129/2a11efdd-0227-40c7-8422-017d5404268e)

Każda atrakcja powinna móc zdefiniować n tagów jako require i n tagów jako reject (bez sprawdzania czy to ma sens)

**Comment by WertiPL** [comment]
Dodałem oznaczenie 0,1,2,3 do excela z POI
