### ISSUE TITLE
Scenariusz prezentacji

### ISSUE THREAD

**Issue by damiankreft** [EngineerDiplomaTeam/city-map-planner#87]
Należy opracować/odświeżyć scenariusz prezentacji w oparciu o najnowsze informacje uzyskane od prowadzących.

**Comment by WertiPL** [comment]
1. Temat i zespół
2. Pomysł
3. Cel
4. Opis problemu
5. Prezentacja aplikacji
6. Podjęte działania
7. Wymagane funkcjonalności
8. Metodyka
9. Komponenty
10. Wzorce projektowe
11. Technologie
12. Narzędzia
13. Architektura systemu
14. Sukcesy/problemy
15. Perspektywy na przyszłość
16. Wkład własny
17. Inne
18. Działanie rozwiązania - demonstracja funkcjonalności.
